### ISSUE TITLE
Alignment not from AMR 3.0

### ISSUE THREAD

**Issue by Carlosml26** [ablodge/leamr#5]
I have found that the gold test data set  have some sentences that are not from AMR 3.0 or for Little prince corpus. Where are they from? Where can I find them?

edinburgh_1003.1
edinburgh_1003.2
edinburgh_1003.3
edinburgh_1003.4
edinburgh_1003.5
edinburgh_1003.6
edinburgh_1003.7
edinburgh_1003.8
edinburgh_1003.9
edinburgh_1003.10
NATHANS_EXAMPLE
AUSTINS_EXAMPLE

**Comment by ablodge** [comment]
These additional AMRs are contained in `data-release/amrs/additional_amrs.txt`. The test data is based on 200 sentences from [Szubert et al. (2018)](https://www.aclweb.org/anthology/N18-1106/) which includes randomly sampled sentences and hand picked sentences with complex linguistic structure. If you run build_data.py, it will build the test and dev AMR files and place them in `data-release/amrs`.
