### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by denlogv** [ablodge/leamr#7]
Could you, please, also upload the pretrained models, or show how they can be accessed? Because right now, it seems that the repository only has metadata about them, which results into the following error, when running `python align_with_pretrained_model.py -t <unaligned amr file> --subgraph-model ldc+little_prince.subgraph_aligner.params --relation-model ldc+little_prince.relation_aligner.params --reentrancy-model ldc+little_prince.reentrancy_aligner.params `:

```
_pickle.UnpicklingError:` invalid load key, 'v'.
```

**Comment by PhillipHoward** [comment]
I had this same issue and resolved it by downloading the model files directly:

```
wget https://github.com/ablodge/leamr/raw/master/ldc%2Blittle_prince.reentrancy_aligner.params
wget https://github.com/ablodge/leamr/raw/master/ldc%2Blittle_prince.relation_aligner.params
wget https://github.com/ablodge/leamr/raw/master/ldc%2Blittle_prince.subgraph_aligner.params
```

It seems that these files are not fully downloaded when you clone the repo due to their large size.

**Comment by ablodge** [comment]
Thanks! I'll add instructions to the README.
